### ISSUE TITLE
Models *and one-sided walls*.

### ISSUE THREAD

**Issue by daveleack** [sylvinus/imgfab#2]
Hiya,
Wouldn't it be sensible (since this is being promoted through SketchFab) to use models instead of pictures? You could put little podia in the middle of the gallery room and load the most viewed (or least, or selectable) model files from sketchfab, do a bounding box size check, then place them atop the pedestals.

Just a thought.

Material selection might be an issue though. Maybe default to a simple matcap.

Also! If you have faces set to one sided, so with reversed normals they become transparent, I assume the InstaMuseum thumbnail on SketchFab wouldn't just look like a grey box, you _should_ be able to see at least two walls and the floor, which would look loads better.

**Comment by sylvinus** [comment]
Hi @daveleack!

Inserting models into the layouts is an interesting idea, hadn't thought of that before! I'll discuss this with the Sketchfab team!

I don't get your last point on the thumbnails. We set a particular camera angle in the 3D settings on Sketchfab so the thumbnail is done from within the room. Isn't that the case for you?

**Comment by daveleack** [comment]
I don't know if I've manually changed the thumbnail on my gallery model, but if you take a look, it looks like it's outside. https://sketchfab.com/dazirius/models
It would be interesting to have it outside but with the frontmost walls see-through (one-way, normal pointing away from the camera). No major issue, just thought it would look cool :D

**Comment by sylvinus** [comment]
OK! It does seem that some of the latest models have a wrong thumbnail. I'll investigate!
https://sketchfab.com/models?tags=instamuseum

**Comment by sylvinus** [comment]
The thumbnails have been fixed, all new models should be good. Sorry for the inconvenience!
